Repository AY2425S2-CS2103T-W12-4/tp, pull requests merged in 2025-04, with the labels that each got.

#196 Update class command to preserve assignments
  src/main/java/tassist/address/logic/commands/ClassCommand.java
  src/test/java/tassist/address/logic/commands/ClassCommandTest.java
Labels: type.Bug, severity.High, alpha-bug

#195 Prevent duplicate syntax from being accepted when using class command
  src/main/java/tassist/address/logic/parser/ClassCommandParser.java
  src/test/java/tassist/address/logic/parser/ClassCommandParserTest.java
Labels: type.Bug, severity.High, alpha-bug

#193 Update github command to preserve assignments
  src/main/java/tassist/address/logic/commands/GithubCommand.java
  src/test/java/tassist/address/logic/commands/GithubCommandTest.java
Labels: type.Bug, severity.High, alpha-bug

#197 Prevent duplicate syntax from being accepted when using github command
  src/main/java/tassist/address/logic/parser/GithubCommandParser.java
  src/test/java/tassist/address/logic/parser/GithubCommandParserTest.java
Labels: type.Bug, severity.High, alpha-bug

#173 Update delete command sequence diagram
  docs/diagrams/DeleteSequenceDiagram.puml
Labels: type.Task, priority.High

#200 Handle Assignment duplicate name
  src/main/java/tassist/address/model/timedevents/TimedEvent.java
  src/test/java/tassist/address/model/timedevents/AssignmentTest.java
Labels: type.Bug, severity.Medium, alpha-bug

#201 Add tostring methods for all commands
  src/main/java/tassist/address/logic/commands/ClassCommand.java
  src/main/java/tassist/address/logic/commands/ClearCommand.java
  src/main/java/tassist/address/logic/commands/GithubCommand.java
  src/main/java/tassist/address/logic/commands/UnassignCommand.java
  src/main/java/tassist/address/logic/commands/ViewCommand.java
  src/test/java/tassist/address/logic/commands/ClassCommandTest.java
  src/test/java/tassist/address/logic/commands/ClearCommandTest.java
  src/test/java/tassist/address/logic/commands/GithubCommandTest.java
  src/test/java/tassist/address/logic/commands/UnassignCommandTest.java
  src/test/java/tassist/address/logic/commands/ViewCommandTest.java
Labels: type.Bug, priority.Medium, severity.Low

#203 Fix person not found message
  src/main/java/tassist/address/logic/Messages.java
Labels: type.Bug, priority.Low, severity.VeryLow

#202 Standardize person equals
  src/main/java/tassist/address/model/person/Person.java
  src/test/java/tassist/address/model/person/PersonTest.java
Labels: type.Bug, priority.Low, severity.Medium

#204 Update find command
  src/main/java/tassist/address/commons/util/StringUtil.java
  src/main/java/tassist/address/logic/commands/FindCommand.java
  src/main/java/tassist/address/logic/parser/FindCommandParser.java
  src/test/java/tassist/address/commons/util/StringUtilTest.java
  src/test/java/tassist/address/logic/commands/FindCommandTest.java
  src/test/java/tassist/address/logic/parser/FindCommandParserTest.java
  src/test/java/tassist/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: type.Enhancement, priority.Low, alpha-bug

#207 Disallow assigning overdue timed events
  src/main/java/tassist/address/logic/commands/AssignCommand.java
  src/test/java/tassist/address/logic/commands/AssignmentCommandTest.java
Labels: type.Bug, priority.Medium, alpha-bug

#209 Add Progress tests
  src/test/java/tassist/address/model/person/ProgressTest.java
Labels: type.Task, priority.Medium

#224 Update browserService implementation
  src/main/java/tassist/address/logic/LogicManager.java
  src/main/java/tassist/address/logic/commands/OpenCommand.java
  src/test/java/tassist/address/logic/LogicManagerTest.java
  src/test/java/tassist/address/logic/browser/DesktopBrowserServiceTest.java
  src/test/java/tassist/address/logic/commands/OpenCommandTest.java
Labels: type.Bug, priority.Low, severity.VeryLow, alpha-bug

#237 Update FindCommand in UG
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#235 Update DeleteCommand in UG
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#230 Update UI and Model section of Developer Guide
  docs/DeveloperGuide.md
  docs/images/ModelClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: type.Enhancement, priority.Medium

#215 Disallow "No tutorial assigned" to remove class
  src/main/java/tassist/address/logic/commands/ClassCommand.java
  src/main/java/tassist/address/logic/parser/ClassCommandParser.java
  src/main/java/tassist/address/model/person/ClassNumber.java
  src/test/java/tassist/address/logic/parser/ClassCommandParserTest.java
Labels: type.Bug, priority.Medium, alpha-bug

#219 Update list command 'course' --> 'class'
  src/main/java/tassist/address/logic/commands/ListCommand.java
  src/main/java/tassist/address/logic/parser/ListCommandParser.java
  src/main/java/tassist/address/model/person/Person.java
  src/test/java/tassist/address/logic/commands/ListCommandTest.java
  src/test/java/tassist/address/logic/parser/AddressBookParserTest.java
  src/test/java/tassist/address/logic/parser/ListCommandParserTest.java
Labels: type.Bug, severity.High, alpha-bug

#205 Allow github to have multiple "no assigned github"
  src/main/java/tassist/address/logic/commands/GithubCommand.java
  src/main/java/tassist/address/logic/parser/GithubCommandParser.java
  src/main/java/tassist/address/model/person/Github.java
  src/test/java/tassist/address/logic/commands/GithubCommandTest.java
  src/test/java/tassist/address/logic/parser/GithubCommandParserTest.java
Labels: type.Bug, severity.High, alpha-bug

#249 Fix CsvJsonConverter Test Cases
  src/main/java/tassist/address/model/person/Person.java
  src/main/java/tassist/address/storage/CsvJsonConverter.java
  src/test/data/CsvJsonConverterTest/testConverterFromJson.csv
  src/test/data/CsvJsonConverterTest/testConverterFromJson.json
  src/test/data/CsvJsonConverterTest/valid.csv
  src/test/java/tassist/address/logic/commands/ImportCommandTest.java
  src/test/java/tassist/address/model/person/PersonTest.java
  src/test/java/tassist/address/storage/CsvJsonConverterTest.java
Labels: type.Bug, priority.High, severity.High

#254 Tighten ClassCommand input validation
  src/main/java/tassist/address/logic/parser/ClassCommandParser.java
  src/test/java/tassist/address/logic/parser/ClassCommandParserTest.java
Labels: type.Bug, severity.High, alpha-bug

#252 Tighten GithubCommand input validation
  src/main/java/tassist/address/logic/commands/GithubCommand.java
  src/main/java/tassist/address/logic/parser/GithubCommandParser.java
  src/test/java/tassist/address/logic/parser/GithubCommandParserTest.java
Labels: type.Bug, severity.High, alpha-bug

#246 Edit email constraints
  src/main/java/tassist/address/model/person/Email.java
  src/test/data/CsvJsonConverterTest/testConverterFromJson.csv
  src/test/data/CsvJsonConverterTest/testConverterFromJson.json
  src/test/data/CsvJsonConverterTest/valid.csv
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/tassist/address/logic/commands/CommandTestUtil.java
  src/test/java/tassist/address/logic/parser/ParserUtilTest.java
  src/test/java/tassist/address/model/person/EmailTest.java
  src/test/java/tassist/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/tassist/address/storage/CsvJsonConverterTest.java
  src/test/java/tassist/address/testutil/AssignCommandTestUtil.java
  src/test/java/tassist/address/testutil/PersonBuilder.java
  src/test/java/tassist/address/testutil/TypicalAssignments.java
  src/test/java/tassist/address/testutil/TypicalPersons.java
Labels: severity.High, alpha-bug

#255 Update UG - import and export commands
  docs/UserGuide.md
Labels: type.Task, priority.High

#260 Correct sample data email domain
  src/main/java/tassist/address/model/util/SampleDataUtil.java
Labels: type.Bug, priority.High, severity.Low

#261 Update user guide - progress comand
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#229 Update User Guide
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#263 Release v1.5
  build.gradle
  docs/images/Ui.png
  docs/index.md
  src/main/java/tassist/address/MainApp.java
Labels: type.Task, priority.High

#243 Add Examples to Github Message
  src/main/java/tassist/address/model/person/Github.java
  src/test/java/tassist/address/model/person/GithubTest.java
Labels: type.Bug, priority.High, severity.Medium, alpha-bug

#268 Update Developer Guide
  docs/DeveloperGuide.md
Labels: type.Task, priority.Low

#265 Change String 'fullName' field into 'value' in Name class
  src/main/java/tassist/address/logic/commands/ListCommand.java
  src/main/java/tassist/address/model/person/Name.java
  src/main/java/tassist/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/tassist/address/storage/JsonAdaptedPerson.java
  src/main/java/tassist/address/ui/PersonCard.java
  src/test/java/tassist/address/logic/commands/CommandTestUtil.java
  src/test/java/tassist/address/logic/commands/ListCommandTest.java
  src/test/java/tassist/address/model/AddressBookModelTest.java
  src/test/java/tassist/address/model/ModelManagerTest.java
  src/test/java/tassist/address/testutil/PersonUtil.java
Labels: type.Epic, type.Enhancement, priority.Low, severity.Low

#272 Fix edit duplicate entries for phone, email, GitHub
  src/main/java/tassist/address/logic/commands/EditCommand.java
  src/test/data/CsvJsonConverterTest/valid.csv
  src/test/java/tassist/address/logic/commands/EditCommandTest.java
  src/test/java/tassist/address/testutil/TypicalPersons.java
Labels: severity.High, alpha-bug

#274 Improve code quality
  src/main/java/tassist/address/logic/commands/AddCommand.java
  src/main/java/tassist/address/logic/commands/AssignmentCommand.java
  src/main/java/tassist/address/logic/commands/ClassCommand.java
  src/main/java/tassist/address/logic/commands/DeleteCommand.java
  src/main/java/tassist/address/logic/commands/EditCommand.java
  src/main/java/tassist/address/logic/commands/ExportCommand.java
  src/main/java/tassist/address/logic/commands/FindCommand.java
  src/main/java/tassist/address/logic/commands/GithubCommand.java
  src/main/java/tassist/address/logic/commands/HelpCommand.java
  src/main/java/tassist/address/logic/commands/ImportCommand.java
  src/main/java/tassist/address/logic/commands/ListCommand.java
  src/main/java/tassist/address/logic/commands/OpenCommand.java
  src/main/java/tassist/address/logic/commands/ProgressCommand.java
  src/main/java/tassist/address/logic/commands/RepoCommand.java
  src/main/java/tassist/address/logic/commands/UnassignCommand.java
  src/main/java/tassist/address/logic/parser/ListCommandParser.java
  src/main/java/tassist/address/logic/parser/RepoCommandParser.java
  src/main/java/tassist/address/model/person/Github.java
  src/main/java/tassist/address/model/person/Name.java
  src/main/java/tassist/address/model/person/Repository.java
  src/main/java/tassist/address/model/person/StudentId.java
  src/test/java/tassist/address/logic/commands/RepoCommandTest.java
  src/test/java/tassist/address/logic/parser/RepoCommandParserTest.java
Labels: type.Bug, priority.High, severity.High, alpha-bug

#342 Edit phone number limit
  src/main/java/tassist/address/logic/commands/EditCommand.java
  src/main/java/tassist/address/model/person/Email.java
  src/main/java/tassist/address/model/person/Phone.java
Labels: type.Bug, severity.Medium

#341 Update User Guide
  docs/UserGuide.md
  src/main/java/tassist/address/model/person/Repository.java
Labels: type.Bug, priority.High, severity.High, alpha-bug

#344 Add class command sequence diagram
  docs/diagrams/ClassSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task, priority.High

#346 Tighten list command input validation
  src/main/java/tassist/address/logic/parser/ListCommandParser.java
  src/test/java/tassist/address/logic/parser/ListCommandParserTest.java
Labels: type.Bug, severity.Medium

#348 Update list command user guide
  docs/UserGuide.md
Labels: type.Task

#350 Add square bracket
  src/main/java/tassist/address/logic/commands/AddCommand.java
Labels: type.Bug, severity.VeryLow

#355 Update DG - Add use cases for the list command
  docs/DeveloperGuide.md
  src/main/java/tassist/address/logic/commands/ListCommand.java
Labels: type.Task

#351 Update Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
Labels: type.Bug, priority.Medium, severity.Medium

#353 Update UG to fix bugs
  docs/UserGuide.md
Labels: type.Bug, severity.Medium

#361 Branch make name strictly numerical
  docs/UserGuide.md
  src/main/java/tassist/address/logic/parser/FindCommandParser.java
  src/main/java/tassist/address/model/person/Name.java
  src/test/java/tassist/address/logic/parser/FindCommandParserTest.java
  src/test/java/tassist/address/model/person/NameTest.java
Labels: type.Bug, priority.Medium, severity.Medium, alpha-bug

#357 Add invalid path check for windows in import and export
  src/main/java/tassist/address/logic/parser/ImportCommandParser.java
  src/main/java/tassist/address/logic/parser/ParserUtil.java
  src/test/java/tassist/address/logic/parser/ParserUtilTest.java
Labels: type.Bug, priority.High, severity.High

#364 Update the tips section in the User Guide
  docs/UserGuide.md
Labels: type.Task

#358 Class Command - Add support for labs
  docs/UserGuide.md
  src/main/java/tassist/address/logic/commands/ClassCommand.java
  src/main/java/tassist/address/model/person/ClassNumber.java
  src/test/java/tassist/address/logic/commands/ClassCommandTest.java
  src/test/java/tassist/address/logic/commands/CommandTestUtil.java
  src/test/java/tassist/address/logic/parser/ClassCommandParserTest.java
  src/test/java/tassist/address/logic/parser/ParserUtilTest.java
Labels: type.Bug, priority.High, severity.High

#370 Fix list command error message
  src/main/java/tassist/address/logic/commands/ListCommand.java
Labels: type.Bug

#372 UML Remove Angled Brackets
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/images/LogicClassDiagram.png
  docs/images/ParserClasses.png
Labels: type.Bug, priority.High, severity.High

#373 Update calendar view
  src/main/java/tassist/address/ui/CalendarView.java
  src/main/resources/view/CalendarView.fxml
Labels: type.Enhancement, priority.Low, severity.Low

#371 Standardize parameter order of assigncommand
  docs/UserGuide.md
  src/main/java/tassist/address/logic/commands/AssignCommand.java
  src/main/java/tassist/address/logic/parser/AssignCommandParser.java
  src/test/java/tassist/address/logic/parser/AssignCommandParserTest.java
Labels: type.Enhancement, priority.Low, severity.Low

#376 Add Documentation to README
  README.md
  docs/UserGuide.md
Labels: type.Enhancement, priority.Low

#362 Update Developer Guide - Add `Import` and `Export` Use Cases
  docs/DeveloperGuide.md
Labels: type.Bug, priority.High, severity.High

#379 Underline use cases - DG
  docs/DeveloperGuide.md
Labels: type.Bug

#380 Update DG for future implementations
  docs/DeveloperGuide.md
Labels: type.Enhancement, priority.Medium, severity.Medium

#381 PPP Harbour
  docs/team/harbour.md
  docs/team/nano-233.md
Labels: type.Task
