Repository AY2425S2-CS2103T-W12-4/tp, pull requests merged in 2025-03, with the labels that each got.

#5 Add Harbour's photo
  docs/images/nano-233.png
Labels: type.Task, priority.High

#6 Add Sulaksha's photo
  docs/images/crmlatte.png
Labels: type.Task, priority.High

#8 Add Casie's photo
  docs/images/casielim.png
Labels: type.Task, priority.High

#10 Update AboutUs - Kenji
  docs/AboutUs.md
  docs/team/kkenjji.md
Labels: type.Task, priority.High

#14 Update AboutUs - Harbour
  docs/AboutUs.md
  docs/team/harbour.md
Labels: type.Task, priority.High

#15 Update AboutUs - Casie Lim
  docs/AboutUs.md
  docs/team/casielim.md
Labels: type.Task, priority.High

#19 Update AboutUs - Eliza
  docs/AboutUs.md
  docs/team/eliza.md
Labels: type.Task, priority.High

#45 Update project website header and repo
  docs/_config.yml
  docs/_sass/minima/_base.scss
Labels: type.Task, priority.High

#40 Add user stories to developer guide
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#43 Add NFRs to developer guide
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#46 Acknowledge original source code
  README.md
Labels: type.Task, priority.High

#51 Update Ui
  docs/images/Ui.png
Labels: type.Task, priority.High

#53 Update status badge
  README.md
Labels: type.Task, priority.High

#47 Update README
  README.md
Labels: type.Task, priority.High

#59 Add use cases to developer guide
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#55 Add record Github feature
  src/main/java/tassist/address/logic/commands/EditCommand.java
  src/main/java/tassist/address/logic/commands/GithubCommand.java
  src/main/java/tassist/address/logic/parser/AddCommandParser.java
  src/main/java/tassist/address/logic/parser/AddressBookParser.java
  src/main/java/tassist/address/logic/parser/CliSyntax.java
  src/main/java/tassist/address/logic/parser/EditCommandParser.java
  src/main/java/tassist/address/logic/parser/GithubCommandParser.java
  src/main/java/tassist/address/logic/parser/ParserUtil.java
  src/main/java/tassist/address/model/person/Github.java
  src/main/java/tassist/address/model/person/Person.java
  src/main/java/tassist/address/model/util/SampleDataUtil.java
  src/main/java/tassist/address/storage/JsonAdaptedPerson.java
  src/main/java/tassist/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/tassist/address/logic/commands/CommandTestUtil.java
  src/test/java/tassist/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/tassist/address/logic/commands/GithubCommandTest.java
  src/test/java/tassist/address/logic/parser/AddressBookParserTest.java
  src/test/java/tassist/address/logic/parser/GithubCommandParserTest.java
  src/test/java/tassist/address/storage/JsonAdaptedPersonTest.java
  src/test/java/tassist/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/tassist/address/testutil/PersonBuilder.java
  src/test/java/tassist/address/testutil/PersonUtil.java
  src/test/java/tassist/address/testutil/TypicalPersons.java
Labels: type.Epic, priority.High

#65 Create Progress class
  src/main/java/tassist/address/logic/Messages.java
  src/main/java/tassist/address/logic/commands/AddCommand.java
  src/main/java/tassist/address/logic/commands/EditCommand.java
  src/main/java/tassist/address/logic/commands/GithubCommand.java
  src/main/java/tassist/address/logic/parser/AddCommandParser.java
  src/main/java/tassist/address/logic/parser/CliSyntax.java
  src/main/java/tassist/address/logic/parser/EditCommandParser.java
  src/main/java/tassist/address/logic/parser/ParserUtil.java
  src/main/java/tassist/address/model/person/Person.java
  src/main/java/tassist/address/model/person/Progress.java
  src/main/java/tassist/address/model/util/SampleDataUtil.java
  src/main/java/tassist/address/storage/JsonAdaptedPerson.java
  src/main/java/tassist/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/tassist/address/logic/LogicManagerTest.java
  src/test/java/tassist/address/logic/commands/CommandTestUtil.java
  src/test/java/tassist/address/logic/commands/EditCommandTest.java
  src/test/java/tassist/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/tassist/address/logic/parser/AddCommandParserTest.java
  src/test/java/tassist/address/logic/parser/ParserUtilTest.java
  src/test/java/tassist/address/model/person/PersonTest.java
  src/test/java/tassist/address/storage/JsonAdaptedPersonTest.java
  src/test/java/tassist/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/tassist/address/testutil/PersonBuilder.java
  src/test/java/tassist/address/testutil/PersonUtil.java
  src/test/java/tassist/address/testutil/TypicalPersons.java
Labels: type.Epic, priority.High

#60 Create Student ID class
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  src/main/java/tassist/address/logic/Messages.java
  src/main/java/tassist/address/logic/commands/AddCommand.java
  src/main/java/tassist/address/logic/commands/EditCommand.java
  src/main/java/tassist/address/logic/commands/GithubCommand.java
  src/main/java/tassist/address/logic/parser/AddCommandParser.java
  src/main/java/tassist/address/logic/parser/CliSyntax.java
  src/main/java/tassist/address/logic/parser/EditCommandParser.java
  src/main/java/tassist/address/logic/parser/ParserUtil.java
  src/main/java/tassist/address/model/person/Person.java
  src/main/java/tassist/address/model/person/StudentId.java
  src/main/java/tassist/address/model/util/SampleDataUtil.java
  src/main/java/tassist/address/storage/JsonAdaptedPerson.java
  src/main/java/tassist/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/tassist/address/logic/LogicManagerTest.java
  src/test/java/tassist/address/logic/commands/CommandTestUtil.java
  src/test/java/tassist/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/tassist/address/logic/parser/AddCommandParserTest.java
  src/test/java/tassist/address/logic/parser/ParserUtilTest.java
  src/test/java/tassist/address/model/person/PersonTest.java
  src/test/java/tassist/address/storage/JsonAdaptedPersonTest.java
  src/test/java/tassist/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/tassist/address/testutil/PersonBuilder.java
  src/test/java/tassist/address/testutil/PersonUtil.java
  src/test/java/tassist/address/testutil/TypicalPersons.java
Labels: type.Epic, priority.High

#74 Fix UI Bug
  src/main/java/tassist/address/ui/PersonCard.java
Labels: type.Bug, severity.High

#68 Add support for confirmation of commands
  src/main/java/tassist/address/logic/LogicManager.java
  src/main/java/tassist/address/logic/commands/CommandResult.java
  src/main/java/tassist/address/logic/commands/ConfirmableCommand.java
  src/main/java/tassist/address/logic/commands/DeleteCommand.java
  src/test/java/tassist/address/logic/LogicManagerTest.java
  src/test/java/tassist/address/logic/commands/CommandResultTest.java
  src/test/java/tassist/address/logic/commands/DeleteCommandTest.java
Labels: type.Enhancement, priority.Low

#70 Update View List Feature
  src/main/java/tassist/address/logic/commands/ListCommand.java
  src/main/java/tassist/address/logic/parser/AddressBookParser.java
  src/main/java/tassist/address/logic/parser/CliSyntax.java
  src/main/java/tassist/address/logic/parser/ListCommandParser.java
  src/main/java/tassist/address/model/Model.java
  src/main/java/tassist/address/model/ModelManager.java
  src/main/java/tassist/address/model/person/Person.java
  src/test/java/tassist/address/logic/LogicManagerTest.java
  src/test/java/tassist/address/logic/commands/AddCommandTest.java
  src/test/java/tassist/address/logic/commands/ListCommandTest.java
  src/test/java/tassist/address/logic/parser/ListCommandParserTest.java
Labels: type.Enhancement, priority.Medium

#69 Add assign tutorial class
  src/main/java/tassist/address/logic/Messages.java
  src/main/java/tassist/address/logic/commands/ClassCommand.java
  src/main/java/tassist/address/logic/commands/EditCommand.java
  src/main/java/tassist/address/logic/commands/GithubCommand.java
  src/main/java/tassist/address/logic/parser/AddCommandParser.java
  src/main/java/tassist/address/logic/parser/AddressBookParser.java
  src/main/java/tassist/address/logic/parser/ClassCommandParser.java
  src/main/java/tassist/address/logic/parser/CliSyntax.java
  src/main/java/tassist/address/logic/parser/EditCommandParser.java
  src/main/java/tassist/address/logic/parser/ParserUtil.java
  src/main/java/tassist/address/model/person/ClassNumber.java
  src/main/java/tassist/address/model/person/Person.java
  src/main/java/tassist/address/model/util/SampleDataUtil.java
  src/main/java/tassist/address/storage/JsonAdaptedPerson.java
  src/main/java/tassist/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/tassist/address/logic/commands/ClassCommandTest.java
  src/test/java/tassist/address/logic/commands/CommandTestUtil.java
  src/test/java/tassist/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/tassist/address/logic/parser/AddressBookParserTest.java
  src/test/java/tassist/address/logic/parser/ClassCommandParserTest.java
  src/test/java/tassist/address/logic/parser/ParserUtilTest.java
  src/test/java/tassist/address/model/person/ClassNumberTest.java
  src/test/java/tassist/address/model/person/PersonTest.java
  src/test/java/tassist/address/storage/JsonAdaptedPersonTest.java
  src/test/java/tassist/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/tassist/address/testutil/PersonBuilder.java
  src/test/java/tassist/address/testutil/PersonUtil.java
  src/test/java/tassist/address/testutil/TypicalPersons.java
Labels: type.Epic, type.Story, priority.High

#80 Fix GitHub ui bug
  src/main/java/tassist/address/logic/Messages.java
  src/main/java/tassist/address/logic/commands/EditCommand.java
  src/main/java/tassist/address/model/person/ClassNumber.java
  src/main/java/tassist/address/model/person/Person.java
  src/main/java/tassist/address/ui/PersonCard.java
  src/test/java/tassist/address/model/person/PersonTest.java
  src/test/java/tassist/address/testutil/PersonBuilder.java
  src/test/java/tassist/address/testutil/TypicalPersons.java
Labels: type.Bug, priority.High

#82 Add support for themes
  .gitignore
  src/main/java/tassist/address/commons/core/GuiSettings.java
  src/main/java/tassist/address/ui/CommandBox.java
  src/main/java/tassist/address/ui/MainWindow.java
  src/main/java/tassist/address/ui/PersonCard.java
  src/main/java/tassist/address/ui/UiManager.java
  src/main/resources/view/BaseTheme.css
  src/main/resources/view/BrightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PinkTheme.css
  src/main/resources/view/Theme.css
Labels: type.Enhancement, priority.Low

#84 Add open github command
  src/main/java/tassist/address/logic/LogicManager.java
  src/main/java/tassist/address/logic/browser/BrowserService.java
  src/main/java/tassist/address/logic/browser/DesktopBrowserService.java
  src/main/java/tassist/address/logic/commands/OpenCommand.java
  src/main/java/tassist/address/logic/parser/AddressBookParser.java
  src/main/java/tassist/address/logic/parser/OpenCommandParser.java
  src/test/java/tassist/address/logic/LogicManagerTest.java
  src/test/java/tassist/address/logic/browser/DesktopBrowserServiceTest.java
  src/test/java/tassist/address/logic/commands/OpenCommandTest.java
  src/test/java/tassist/address/logic/parser/AddressBookParserTest.java
  src/test/java/tassist/address/logic/parser/OpenCommandParserTest.java
Labels: type.Epic, priority.Medium

#87 Improve UI quality
  src/main/java/tassist/address/logic/Messages.java
  src/main/java/tassist/address/logic/commands/GithubCommand.java
  src/main/java/tassist/address/ui/MainWindow.java
  src/main/java/tassist/address/ui/UiManager.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/Theme.css
Labels: type.Enhancement, type.Bug, priority.Medium, severity.Medium

#90 Remove address, fix ClassNumber bug
  src/main/java/tassist/address/logic/Messages.java
  src/main/java/tassist/address/logic/commands/AddCommand.java
  src/main/java/tassist/address/logic/commands/ClassCommand.java
  src/main/java/tassist/address/logic/commands/EditCommand.java
  src/main/java/tassist/address/logic/commands/GithubCommand.java
  src/main/java/tassist/address/logic/parser/AddCommandParser.java
  src/main/java/tassist/address/logic/parser/ClassCommandParser.java
  src/main/java/tassist/address/logic/parser/CliSyntax.java
  src/main/java/tassist/address/logic/parser/EditCommandParser.java
  src/main/java/tassist/address/logic/parser/ParserUtil.java
  src/main/java/tassist/address/model/person/Address.java
  src/main/java/tassist/address/model/person/Person.java
  src/main/java/tassist/address/model/util/SampleDataUtil.java
  src/main/java/tassist/address/storage/JsonAdaptedPerson.java
  src/main/java/tassist/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/tassist/address/logic/LogicManagerTest.java
  src/test/java/tassist/address/logic/commands/CommandTestUtil.java
  src/test/java/tassist/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/tassist/address/logic/parser/AddCommandParserTest.java
  src/test/java/tassist/address/logic/parser/EditCommandParserTest.java
  src/test/java/tassist/address/logic/parser/ParserUtilTest.java
  src/test/java/tassist/address/model/AddressBookTest.java
  src/test/java/tassist/address/model/person/AddressTest.java
  src/test/java/tassist/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/tassist/address/model/person/PersonTest.java
  src/test/java/tassist/address/model/person/UniquePersonListTest.java
  src/test/java/tassist/address/storage/JsonAdaptedPersonTest.java
  src/test/java/tassist/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/tassist/address/testutil/PersonBuilder.java
  src/test/java/tassist/address/testutil/PersonUtil.java
  src/test/java/tassist/address/testutil/TypicalPersons.java
Labels: type.Enhancement, type.Bug, priority.High, severity.High

#92 Change usage message of ClassCommand
  src/main/java/tassist/address/logic/commands/ClassCommand.java
  src/main/java/tassist/address/model/person/ClassNumber.java
Labels: type.Enhancement, priority.High

#95 TAssist release v1.3
  src/main/java/tassist/address/MainApp.java
Labels: type.Task, priority.High

#75 Add studentId to Github command
  src/main/java/tassist/address/logic/Messages.java
  src/main/java/tassist/address/logic/commands/GithubCommand.java
  src/main/java/tassist/address/logic/parser/GithubCommandParser.java
  src/test/java/tassist/address/logic/commands/CommandTestUtil.java
  src/test/java/tassist/address/logic/commands/GithubCommandTest.java
  src/test/java/tassist/address/logic/parser/AddressBookParserTest.java
  src/test/java/tassist/address/logic/parser/GithubCommandParserTest.java
Labels: type.Story, priority.High

#96 Update user guide v1.3
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/UiDesign.png
  docs/images/UserGuideFindCommand1.png
Labels: type.Task, priority.Medium

#100 Create StudentIdTest
  src/main/java/tassist/address/model/person/StudentId.java
  src/test/java/tassist/address/model/person/StudentIdTest.java
Labels: type.Enhancement, priority.Medium

#108 Improve formatting
  src/test/java/tassist/address/model/person/StudentIdTest.java
Labels: type.Enhancement, priority.Low

#101 Add studentId to DeleteCommand
  src/main/java/tassist/address/logic/commands/DeleteCommand.java
  src/main/java/tassist/address/logic/parser/DeleteCommandParser.java
  src/test/java/tassist/address/logic/commands/DeleteCommandTest.java
  src/test/java/tassist/address/logic/parser/AddressBookParserTest.java
  src/test/java/tassist/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Enhancement, priority.Medium

#114 Update UI
  docs/images/Ui.png
Labels: type.Task, priority.Low

#104 Check GitHub for duplicates
  src/main/java/tassist/address/logic/commands/DeleteCommand.java
  src/main/java/tassist/address/logic/commands/GithubCommand.java
  src/test/java/tassist/address/logic/commands/DeleteCommandTest.java
  src/test/java/tassist/address/logic/commands/GithubCommandTest.java
Labels: type.Enhancement, priority.High

#112 Update user guide
  docs/UserGuide.md
Labels: type.Task, priority.High

#106 Create GithubTest class
  src/main/java/tassist/address/logic/commands/AddCommand.java
  src/main/java/tassist/address/logic/parser/AddCommandParser.java
  src/main/java/tassist/address/model/person/Github.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/tassist/address/model/person/GithubTest.java
  src/test/java/tassist/address/testutil/PersonBuilder.java
Labels: type.Enhancement, priority.Medium

#116 Update list command message and sorting feature
  src/main/java/tassist/address/logic/commands/ListCommand.java
  src/test/java/tassist/address/logic/commands/ListCommandTest.java
Labels: type.Enhancement, type.Task, priority.Medium

#120 Remove support for duplicate Student ID
  src/main/java/tassist/address/logic/commands/AddCommand.java
  src/main/java/tassist/address/model/person/Person.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/tassist/address/logic/commands/CommandTestUtil.java
  src/test/java/tassist/address/model/person/PersonTest.java
  src/test/java/tassist/address/testutil/TypicalPersons.java
Labels: type.Bug, priority.High, severity.High

#140 Create ProjectTeam
  docs/UserGuide.md
  src/main/java/tassist/address/logic/Messages.java
  src/main/java/tassist/address/logic/commands/AddCommand.java
  src/main/java/tassist/address/logic/commands/ClassCommand.java
  src/main/java/tassist/address/logic/commands/EditCommand.java
  src/main/java/tassist/address/logic/commands/GithubCommand.java
  src/main/java/tassist/address/logic/commands/ListCommand.java
  src/main/java/tassist/address/logic/parser/AddCommandParser.java
  src/main/java/tassist/address/logic/parser/CliSyntax.java
  src/main/java/tassist/address/logic/parser/EditCommandParser.java
  src/main/java/tassist/address/logic/parser/ParserUtil.java
  src/main/java/tassist/address/model/person/Person.java
  src/main/java/tassist/address/model/person/ProjectTeam.java
  src/main/java/tassist/address/model/person/StudentId.java
  src/main/java/tassist/address/model/util/SampleDataUtil.java
  src/main/java/tassist/address/storage/JsonAdaptedPerson.java
  src/main/java/tassist/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/tassist/address/logic/LogicManagerTest.java
  src/test/java/tassist/address/logic/commands/AddCommandTest.java
  src/test/java/tassist/address/logic/commands/CommandTestUtil.java
  src/test/java/tassist/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/tassist/address/logic/commands/ListCommandTest.java
  src/test/java/tassist/address/logic/parser/AddCommandParserTest.java
  src/test/java/tassist/address/logic/parser/EditCommandParserTest.java
  src/test/java/tassist/address/model/person/PersonTest.java
  src/test/java/tassist/address/model/person/ProjectTeamTest.java
  src/test/java/tassist/address/storage/JsonAdaptedPersonTest.java
  src/test/java/tassist/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/tassist/address/testutil/PersonBuilder.java
  src/test/java/tassist/address/testutil/PersonUtil.java
  src/test/java/tassist/address/testutil/TypicalPersons.java
Labels: type.Epic, priority.High

#127 Add student id to class command
  src/main/java/tassist/address/logic/commands/ClassCommand.java
  src/main/java/tassist/address/logic/parser/ClassCommandParser.java
  src/test/java/tassist/address/logic/commands/ClassCommandTest.java
  src/test/java/tassist/address/logic/commands/CommandTestUtil.java
  src/test/java/tassist/address/logic/parser/ClassCommandParserTest.java
Labels: type.Enhancement, priority.Medium

#138 Add student ID to FindCommand
  src/main/java/tassist/address/logic/commands/FindCommand.java
  src/main/java/tassist/address/logic/parser/FindCommandParser.java
  src/test/java/tassist/address/logic/commands/FindCommandTest.java
  src/test/java/tassist/address/logic/parser/FindCommandParserTest.java
Labels: type.Enhancement, priority.Medium

#142 Update help command link
  src/main/java/tassist/address/logic/browser/DesktopBrowserService.java
  src/main/java/tassist/address/logic/commands/HelpCommand.java
  src/main/java/tassist/address/ui/HelpWindow.java
  src/main/java/tassist/address/ui/MainWindow.java
  src/test/java/tassist/address/logic/browser/DesktopBrowserServiceTest.java
  src/test/java/tassist/address/logic/commands/HelpCommandTest.java
  src/test/java/tassist/address/logic/parser/AddressBookParserTest.java
Labels: type.Task, priority.High

#146 Add assertions
  build.gradle
  src/main/java/tassist/address/logic/commands/AddCommand.java
  src/main/java/tassist/address/logic/commands/DeleteCommand.java
  src/main/java/tassist/address/model/AddressBook.java
  src/main/java/tassist/address/model/ModelManager.java
  src/main/java/tassist/address/model/person/UniquePersonList.java
Labels: type.Task, priority.Medium

#150 Fix assignment status to update automatically on UI
  src/main/java/tassist/address/logic/commands/AssignCommand.java
Labels: type.Bug, priority.Medium, severity.Medium

#137 Add duplicate prefix check for assignment related commands
  src/main/java/tassist/address/logic/parser/AssignmentCommandParser.java
  src/test/java/tassist/address/logic/parser/AddCommandParserTest.java
  src/test/java/tassist/address/logic/parser/AssignmentCommandParserTest.java
Labels: type.Bug, priority.High, severity.High

#151 Fix assign with index
  src/main/java/tassist/address/logic/commands/AssignCommand.java
Labels: type.Bug, priority.Medium, severity.Medium

#131 Add support to view TimedEvents
  src/main/java/tassist/address/logic/Logic.java
  src/main/java/tassist/address/logic/LogicManager.java
  src/main/java/tassist/address/model/AddressBookModel.java
  src/main/java/tassist/address/model/Model.java
  src/main/java/tassist/address/model/ModelManager.java
  src/main/java/tassist/address/ui/CalendarView.java
  src/main/java/tassist/address/ui/MainWindow.java
  src/main/java/tassist/address/ui/TimeEventCard.java
  src/main/java/tassist/address/ui/TimeEventListPanel.java
  src/main/resources/view/BaseTheme.css
  src/main/resources/view/BrightTheme.css
  src/main/resources/view/CalendarView.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PinkTheme.css
  src/main/resources/view/TimeEventCard.fxml
  src/main/resources/view/TimeEventListPanel.fxml
  src/test/java/tassist/address/logic/commands/AddCommandTest.java
Labels: type.Enhancement, priority.Low

#156 Add hotkeys to theme and view
  src/main/java/tassist/address/ui/CommandBox.java
  src/main/java/tassist/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement, priority.Low

#154 Standardize assignment related testing
  src/main/java/tassist/address/logic/commands/AssignmentCommand.java
  src/test/java/tassist/address/logic/commands/CommandTestUtil.java
  src/test/java/tassist/address/logic/commands/ViewCommandTest.java
  src/test/java/tassist/address/logic/parser/AssignCommandParserTest.java
  src/test/java/tassist/address/logic/parser/AssignmentCommandParserTest.java
Labels: type.Enhancement, priority.Low

#153 Update user guidev1.4
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: type.Task, priority.Medium

#159 Update developer guide v1.4
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#161 Update ModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task, priority.High

#164 Update UI class diagram
  docs/diagrams/UiClassDiagram.puml
Labels: type.Task, priority.High

#175 Add Find command sequence diagram
  docs/UserGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  src/main/java/tassist/address/logic/commands/FindCommand.java
Labels: type.Task, priority.Medium

#171 Add list sequence diagram
  docs/diagrams/ListSequenceDiagram.puml
Labels: type.Task, priority.High

#167 Fix list filtering using ProjectTeam
  src/main/java/tassist/address/logic/commands/ListCommand.java
  src/test/java/tassist/address/logic/commands/ListCommandTest.java
  src/test/java/tassist/address/model/person/ProjectTeamTest.java
Labels: type.Bug, priority.High, severity.High

#168 Update user guide (v1.4)
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium

#187 Edit List error message
  src/main/java/tassist/address/logic/commands/ListCommand.java
Labels: severity.Low, alpha-bug
